Global:
  ManageImages: true
  BootMountPoint: /efi
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
Components:
  ImageDir: /efi/EFI/zbm
  Enabled: false
EFI:
  ImageDir: /efi/EFI/zbm
  Versions: false
  Enabled: true
Kernel:
  CommandLine: ro quiet loglevel=0 rd.udev.log_level=3 rd.vconsole.font=ter-v20b
  Prefix: grubx64
