jobs:
- name: snapjob
  type: snap
  filesystems: {
    "zroot<": true,
  }
  snapshotting:
    type: periodic
    interval: 30m
    prefix: zrepl_
  pruning:
    keep:
      - type: grid
        # grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
        grid: 6x1h | 3x1d
        regex: "^zrepl_"
